var choo = require('choo')
var mainView = require('./temblates/main')
var urlChange = require('./emitters/urlChange')
var protocolChange = require('./emitters/protcolChange')
var hostChange = require('./emitters/hostChange')
var pathChange = require('./emitters/pathChange')
var queryChange = require('./emitters/queryChange')

var app = choo()
app.use(urlChange)
app.use(protocolChange)
app.use(hostChange)
app.use(pathChange)
app.use(queryChange)
app.route('/', mainView)
app.mount('body')
